#include <iostream>
#include <opencv2/opencv.hpp>
#include <stdint.h>
#include "../include/encrypt_kernel.hpp"
#include "../include/prbg_main_plcm.hpp"

int main () {

    double globalKey = 0.123456 ; //used for PRBGmain initialization. is a double value (0,0.5)
    double p = 0.3; //control parameter for the PRBGmain . is a value in (0,0.5)
    int numKeys =128 ;  // each iteration of the PRBG main is a resultant input seed...
                        //...for the future subsequent PRBGas as described by article
    
                        //considering a 768 x 768 Frame.
                        //considering that 128 blocks (equivalent to the assistant threads in the paper) will manage 128 subframes
                        //then we have 128 6x768 subframes.
                        //a particular diffusion operation on a specifc subframe involves 6*768 pixels.
                        //in particular, each of the 6* 768 pixels has a corresponding byte associated for diffusion operation.
                        //so for a subframe, 768* 6 bytes are asssociated to it.
                        //the article says that one result of a particular PRBGa will form 6 bytes of the bytestream used in diffusion in a particular subframe..
                        //hence, the amount of outputs of the PRBGA is 768 * 6 / 6 = 768.
                        //the byte stream of a specific subframe is that of dimension 768*6 .
    const int PRBGAiterations = 768 ; 
    
    double sc ;

    //generating the keys and control parameters that will be fed to future PRBGas
    std::vector<double> keysAndControlPs = generatePRBGMainKeys( globalKey, p, 2*numKeys +1 , &sc ); // +1 for sc generation
    std::vector<uint8_t> byteStreamFinal, output1, output2 ;
    
    //now that the parameter needed to initialize the various PRBGAs are ready, we can launch the wrapper to the kernel dealing with beginning PRGAs execution
    PRBGAKernelWrapper(keysAndControlPs, byteStreamFinal, output1, output2, sc, PRBGAiterations);

    // To access result for block 0 (contains the values generated by the PRBGA assigned to block 0), for example:

    for (int i = 0; i < 128; i++) {
        std::cout << "\n\nPRBGA " << i<< ": 6x768 subframe related bytes which will be used in diffusion op: \n" ;
        //string1 and string2 will be then xored to produce the final byte sequence used in a particular dubframe during diffusion
        
        std::cout << "\n\nstring1  bytes: " ;
        for( int j = 0; j < 768 *6 ; j++){
            std::cout << std::hex << (int)output1[i*(768*6) + j] << " ";
        } 
        std::cout << "\n\nstring2  bytes: " ;
        for( int j = 0; j < 768 *6 ; j++){
            std::cout << std::hex << (int)output2[i*(768*6) + j] << " ";
        }
        std::cout << "\n\nfinal byte string: (which is string1 and string2 xored):  " ;
        for( int j = 0; j < 768 *6 ; j++){
            std::cout << std::hex << (int)byteStreamFinal[i*(768*6) + j] << " ";
        }
    }
    std::cout << std::endl;



    //load the Frame (grayScale mode for now)
    //cv::Mat inputFrame = cv::imread("../testFrames/shrekAndDonkey.png", cv::IMREAD_GRAYSCALE);
    
    //quick check if frame exists
    //if( inputFrame.empty()) {
    //    std::cerr << "Failed to load Frame!\n";
    //    return -1;
    //}
   
    //cv::Mat encryptedFrame(inputFrame.size(), inputFrame.type() );

    //float seed = 0.7f; // for PRBG
    //float k = 0.5f; // control parameter for PiecewiseLinearChaoticMap (PLCM)


    //calling the wrapper for the kernel
    //encryptFrame(inputFrame, encryptedFrame, seed, k);

    //Copying the result back to the host environment
    //cv::imwrite("../testFrames/encrypted_output.png", encryptedFrame);

    //std::cout << "Encryption complete. Saved as encrypted_output.png\n";
    
    return 0;

}