#include <iostream>
#include <opencv2/opencv.hpp>
#include <stdint.h>
#include "../include/encrypt_kernel.hpp"
#include "../include/prbg_main_plcm.hpp"
#include "../include/confusion_kernel.hpp"
#include "../include/diffusion_kernel.hpp"

#define ROUNDS 5

int main () {

    double globalKey = 0.123456 ; //used for PRBGmain initialization. is a double value (0,0.5)
    double p = 0.3; //control parameter for the PRBGmain . is a value in (0,0.5)
    int numKeys =128 ;  /* each iteration of the PRBG main is a resultant input seed...
                        ...for the future subsequent PRBGas as described by article
    
                        considering a 768 x 768 Frame.
                        considering that 128 blocks (equivalent to the assistant threads in the paper) will manage 128 subframes
                        then we have 128 6x768 subframes.
                        a particular diffusion operation on a specifc subframe involves 6*768 pixels.
                        in particular, each of the 6* 768 pixels has a corresponding byte associated for diffusion operation.
                        so for a subframe, 768* 6 bytes are asssociated to it.
                        the article says that one result of a particular PRBGa will form 6 bytes of the bytestream used in diffusion in a particular subframe..
                        hence, the amount of outputs of the PRBGA is 768 * 6 / 6 = 768.
                        the byte stream of a specific subframe is that of dimension 768*6 .
                        */
    const int PRBGAiterations = 768 ; 
    uint64_t sc ;

    //generating the keys and control parameters that will be fed to future PRBGas
    std::vector<double> keysAndControlPs = generatePRBGMainKeys( globalKey, p, 2*numKeys +1 , &sc ) ; // +1 for sc generation
    std::vector<unsigned char> byteStreamFinal, output1, output2 ;
    
    //now that the parameter needed to initialize the various PRBGAs are ready, we can launch the wrapper to the kernel dealing with beginning PRGAs execution
    PRBGAandByteStreamGenWrapper(keysAndControlPs, byteStreamFinal, output1, output2, PRBGAiterations) ;

    // To access result for block 0 (contains the values generated by the PRBGA assigned to block 0), for example:

    //load the Frame (grayScale mode for now)
    cv::Mat inputFrame = cv::imread("testFrames/shrekAndDonkey768x768.png", cv::IMREAD_GRAYSCALE);
    
    //quick check if frame exists
    if( inputFrame.empty()) {
        std::cerr << "Failed to load Frame!\n";
        return -1;
    }

    int width = inputFrame.cols;
    int height = inputFrame.rows;
    printf ("width : %d, height: %d \n", width, height) ;

    cv::Mat current = inputFrame.clone() ;
    std::vector<unsigned char> buffer(width * height);

    int performInverseConfusion = 0;
    int performInverseDiffusion = 0 ;

for( int i = 0; i< ROUNDS; i ++){
//CONFUSION
    
    confusionOpWrapper(current.data, buffer.data(), width, height, sc, performInverseConfusion);  
    current = cv::Mat(height, width, CV_8UC1,buffer.data()).clone();

    //saving image data after the confusion step...
    std::string filenameConfusion = "afterConfusion" + std::to_string(i) +".png" ;
    cv::imwrite(filenameConfusion, current );
    
//DIFFUSION
    
    diffusionOpWrapper( current.data, buffer.data(), byteStreamFinal.data(), width, height, performInverseDiffusion ) ;
    current = cv::Mat(height, width, CV_8UC1, buffer.data()).clone();

    std::string filenameDiffusion = "afterDiffusion" + std::to_string(i) +".png" ;
    cv::imwrite(filenameDiffusion, current );
}

performInverseDiffusion = 1;
performInverseConfusion = 1; // doing the inverse of the confusiion to see if we are able to obtain the original image from the confused one.

for( int i = ROUNDS-1 ; i >=0; i --){

//INVERSE OF DIFFUSION
    //here performing the inverse of the diffusion to see if i am able to obtain the original frame back implying diffusion operations make sense.
    
    diffusionOpWrapper( current.data, buffer.data(), byteStreamFinal.data(), width, height, performInverseDiffusion ) ;
    current = cv::Mat(height, width, CV_8UC1, buffer.data()).clone() ;
    
    std::string filenameInvDiffusion = "afterInvDiffusion" + std::to_string(i) + ".png" ;
    cv::imwrite( filenameInvDiffusion, current) ;    
//INVERSE OF CONFUSION 

    confusionOpWrapper(current.data, buffer.data(), width, height, sc, performInverseConfusion );
    current = cv::Mat(height, width, CV_8UC1, buffer.data()).clone() ;
    
    std::string filenameInvConfusion = "afterInvConfusion" + std::to_string(i) + ".png" ;
    cv::imwrite(filenameInvConfusion, current );

}




    //converting the result back to cv::Mat
    //cv::Mat confusedFrame( height, width, CV_8UC1, confusedVector.data() ) ;

    //calling the wrapper for the kernel
    //encryptFrame(inputFrame, encryptedFrame, seed, k);

    //Copying the result back to the host environment
    //cv::imwrite("../testFrames/encrypted_output.png", encryptedFrame);

    //std::cout << "Encryption complete. Saved as encrypted_output.png\n";
    
    return 0;

}