#include <iostream>
#include <opencv2/opencv.hpp>
#include <stdint.h>
#include <cuda_runtime.h>
#include "../include/encrypt_kernel.hpp"
#include "../include/prbg_main_plcm.hpp"
#include "../include/confusion_kernel.hpp"
#include "../include/diffusion_kernel.hpp"

#define ROUNDS 5
#define NUM_CHANNELS 3 // number RGB channels

int main () {

    int device;
    cudaGetDevice(&device);
    int maxThreadsPerBlock;
    cudaDeviceGetAttribute(&maxThreadsPerBlock, cudaDevAttrMaxThreadsPerBlock, device);
    int maxGridDimX;
    cudaDeviceGetAttribute(&maxGridDimX, cudaDevAttrMaxGridDimX, device);
    int maxGridDimY;
    cudaDeviceGetAttribute(&maxGridDimY, cudaDevAttrMaxGridDimY, device);
    int maxGridDimZ;
    cudaDeviceGetAttribute(&maxGridDimZ, cudaDevAttrMaxGridDimZ, device);

    std::cout << "Max threads per block: " << maxThreadsPerBlock << std::endl;
    std::cout << "Max grid dimensions: (" << maxGridDimX << ", "<< maxGridDimY << ", " << maxGridDimZ << ")" << std::endl;

    //load the Frame (grayScale mode for now)
    cv::Mat inputFrame = cv::imread("testFrames/link960x960.png", cv::IMREAD_COLOR);
    
    //quick check if frame exists
    if( inputFrame.empty()) {
        std::cerr << "Failed to load Frame!\n";
        return -1;
    }

    int width = inputFrame.cols;
    int height = inputFrame.rows;
    int subFrameHeight = 6 ; // keeping the height of the subframe as fixed parameter for now to compute the num of subframes to allocate
    int numSubFrames = width / subFrameHeight ;

    printf ("width : %d, height: %d \n", width, height) ;

    double globalKey = 0.223456 ; //used for PRBGmain initialization. is a double value (0,0.5)
    double p = 0.3; //control parameter for the PRBGmain . is a value in (0,0.5)

    int numKeys =numSubFrames * NUM_CHANNELS ;  /* each iteration of the PRBG main is a resultant input seed...
                        ...for the future subsequent PRBGas as described by article
    
                        considering a 768 x 768 Frame.
                        considering that 128 blocks (equivalent to the assistant threads in the paper) will manage 128 subframes
                        then we have 128 6x768 subframes.
                        a particular diffusion operation on a specifc subframe involves 6*768 pixels.
                        in particular, each of the 6* 768 pixels has a corresponding byte associated for diffusion operation.
                        so for a subframe, 768* 6 bytes are asssociated to it.
                        the article says that one result of a particular PRBGa will form 6 bytes of the bytestream used in diffusion in a particular subframe..
                        hence, the amount of outputs of the PRBGA is 768 * 6 / 6 = 768.
                        the byte stream of a specific subframe is that of dimension 768*6 .
                        */
    const int PRBGAiterations = width ; 
    uint64_t sc ;

    //generating the keys and control parameters that will be fed to future PRBGas
    std::vector<double> keysAndControlPs = generatePRBGMainKeys( globalKey, p, 2*numKeys +1 , &sc ) ; // +1 for sc generation
    std::vector<unsigned char> byteStreamFinal, output1, output2 ;
    
    //now that the parameter needed to initialize the various PRBGAs are ready, we can launch the wrapper to the kernel dealing with beginning PRGAs execution
    PRBGAandByteStreamGenWrapper(keysAndControlPs, byteStreamFinal, output1, output2, PRBGAiterations) ;

    // To access result for block 0 (contains the values generated by the PRBGA assigned to block 0), for example:

    cv::Mat current = inputFrame.clone() ;
    std::vector<unsigned char> buffer(width * height * NUM_CHANNELS); // considering the rgb image , the image information is thrice that of the greyscale

    int performInverseConfusion = 0;
    int performInverseDiffusion = 0 ;

for( int i = 0; i< ROUNDS; i ++){
//CONFUSION
    
    confusionOpWrapper(current.data, buffer.data(), width, height, subFrameHeight, sc, performInverseConfusion); 
 
    current = cv::Mat(height, width, CV_8UC3, buffer.data()).clone();

    std::string filenameConfusion = "testResults/afterConfusion" + std::to_string(i) +".png" ;
    cv::imwrite(filenameConfusion, current );
    
//DIFFUSION
    
    diffusionOpWrapper( current.data, buffer.data(), byteStreamFinal.data(), width, height, subFrameHeight, performInverseDiffusion ) ;
    current = cv::Mat(height, width, CV_8UC3, buffer.data()).clone();

    std::string filenameDiffusion = "testResults/afterDiffusion" + std::to_string(i) +".png" ;
    cv::imwrite(filenameDiffusion, current ); 

}

performInverseDiffusion = 1;
performInverseConfusion = 1; // doing the inverse of the confusiion to see if we are able to obtain the original image from the confused one.

for( int i = ROUNDS-1 ; i >=0; i --){

//INVERSE OF DIFFUSION
    //here performing the inverse of the diffusion to see if i am able to obtain the original frame back implying diffusion operations make sense.
    
    diffusionOpWrapper( current.data, buffer.data(), byteStreamFinal.data(), width, height, subFrameHeight, performInverseDiffusion ) ;
    current = cv::Mat(height, width, CV_8UC3, buffer.data()).clone() ;
    
    std::string filenameInvDiffusion = "testResults/afterInvDiffusion" + std::to_string(i) + ".png" ;
    cv::imwrite( filenameInvDiffusion, current) ;    

//INVERSE OF CONFUSION 

    confusionOpWrapper(current.data, buffer.data(), width, height, subFrameHeight, sc, performInverseConfusion );
    current = cv::Mat(height, width, CV_8UC3, buffer.data()).clone() ;
    
    std::string filenameInvConfusion = "testResults/afterInvConfusion" + std::to_string(i) + ".png" ;
    cv::imwrite(filenameInvConfusion, current );

}

    //converting the result back to cv::Mat
    //cv::Mat confusedFrame( height, width, CV_8UC1, confusedVector.data() ) ;

    //calling the wrapper for the kernel
    //encryptFrame(inputFrame, encryptedFrame, seed, k);

    //Copying the result back to the host environment
    //cv::imwrite("../testFrames/encrypted_output.png", encryptedFrame);

    //std::cout << "Encryption complete. Saved as encrypted_output.png\n";
    
    return 0;

}